TOP=..
include $(TOP)/configure/CONFIG
#=======================================

#protocol files
DATA += wm323.proto
DB += wm323.db

#=======================================
include $(TOP)/configure/RULES
